routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\PhoneController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route homepage

Route::get('/', function () {
    return view('home');
});

// Route Games

Route::resource('games', GameController::class);

// Route Category

Route::resource('categories', CategoryController::class);

// Route Profile

Route::resource('profiles', ProfileController::class);

Route::get('aggiungi/telefono', [PhoneController::class, 'create'])->name('phones.create');
Route::post('salva/numero', [PhoneController::class, 'store'])->name('phones.store');
Route::get('modifica/numero', [PhoneController::class, 'edit'])->name('phones.edit');

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'description', 'img'];

    //One to many con user

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    //Many to many con categories

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Game;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $games = Game::paginate(9);
        return view('games.index', compact('games'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('games.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $game = Auth::user()->games()->create([
            'title'=>$request->title,
            'description'=>$request->description,
            'img'=> $request->file('img') ? $request->file('img')->store('/public/img') : null
            ]);
        $game->categories()->attach($request->categories);

       
        

        return redirect()->back()->with('message', 'Videogioco salvato con successo');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function show(Game $game)
    {
        return view('games.show', compact('game'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function edit(Game $game)
    {
        return view('games.edit', compact('game'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Game $game)
    {
        $game->update([
            'title'=>$request->title,
            'description'=>$request->description,
            'img'=> $request->file('img') ? $request->file('img')->store('/public/img') : null
        ]);
        return redirect(route('games.index'))->with('message', 'Videogioco modificato con successo');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function destroy(Game $game)
    {
        $game->delete();
        return redirect(route('games.index'))->with('message', 'Eliminazione avvenuta con successo');
    }
}

resources/views/games/create.blade.php
<x-layout>
    
    <x-slot name="title">Aggiungi videogioco</x-slot>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 my-5 text-center">
                <h1>Aggiungi un videogioco!!</h1>
            </div>
            @if (session('message'))
                <div class="alert alert-success shadow text-center my-5">
                    <p>{{session('message')}}</p>
                </div>
            @endif
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                <div class="alert alert-danger shadow text-center my-5">
                    <p>{{$error}}</p>
                </div>
                @endforeach
            @endif
            <div class="col-12">
                <form action="{{route('games.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                      <label for="nameGame1" class="form-label">Nome Videogioco</label>
                      <input name="title" type="text" class="form-control" id="nameGame1">
                    </div>
                    <div class="mb-3">
                        <label for="description1" class="form-label">Descrizione videogioco</label>
                        <input name="description" type="text" class="form-control" id="description1">
                    </div>
                    <div class="mb-3">
                        <input name="img" type="file" class="form-control" placeholder="Inserisci un immagine">
                    </div>
                    <select name="categories[]" class="form-select" multiple aria-label="multiple select example">
                        <option selected>Scegli la categoria</option>
                        @foreach ($categories as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                            
                        @endforeach
                        
                      </select>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
            </div>
        </div>
    </div>







</x-layout>

resources/views/games/edit.blade.php
<x-layout>
    
    <x-slot name="title">Modifica videogioco</x-slot>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 my-5 text-center">
                <h1>Modifica videogioco!!</h1>
            </div>
            @if (session('message'))
                <div class="alert alert-success shadow text-center my-5">
                    <p>{{session('message')}}</p>
                </div>
            @endif
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                <div class="alert alert-danger shadow text-center my-5">
                    <p>{{$error}}</p>
                </div>
                @endforeach
            @endif
            <div class="col-12">
                <form action="{{route('games.update', compact('game'))}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                      <label for="nameGame1" class="form-label">Nome Videogioco</label>
                      <input name="title" type="text" class="form-control" id="nameGame1" value="{{$game->title}}">
                    </div>
                    <div class="mb-3">
                        <label for="description1" class="form-label">Descrizione videogioco</label>
                        <input name="description" type="text" class="form-control" id="description1" value="{{$game->description}}">
                    </div>
                    <div class="mb-3">
                        <input name="img" type="file" class="form-control" placeholder="Inserisci un immagine" value="{{$game->img}}">
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
            </div>
        </div>
    </div>







</x-layout>

resources/views/games/index.blade.php
<x-layout>
    <x-slot name="title">Videogiochi</x-slot>
    <style>
        
    </style>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 text-center my-5">
                <h1>Ecco tutti i videogiochi!</h1>
            </div>
            @if (session('message'))
                <div class="alert alert-success shadow text-center my-5">
                    <p>{{session('message')}}</p>
                </div>
            @endif
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                <div class="alert alert-danger shadow text-center my-5">
                    <p>{{$error}}</p>
                </div>
                @endforeach
            @endif
            @foreach ($games as $game)
            <div class="col-12 col-md-4">
                <div class="card my-3">
                    <img src="{{$game->img ? Storage::url($game->img) : 'https://picsum.photos/200'}}" class="card-img-top img-custom" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{$game->title}}</h5>
                      <p class="card-text">Categorie:
                        <ul>
                            @foreach ($game->categories as $category)
                                <li><a href="{{route('categories.show',compact('category'))}}">{{$category->name}}</a></li>
                            @endforeach
                        </ul></p>
                      <p class="card-text">Autore: {{$game->user ? $game->user->name : 'Sconosciuto'}}</p>
                      <p class="card-text">Descrizione: {{$game->description}}</p>
                      <a href="{{route('games.show', compact('game'))}}" class="btn btn-primary">Visualizza dettagli</a>
                      <a href="{{route('games.edit', compact('game'))}}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                      <a href="" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal{{$game->id}}"><i class="fas fa-trash"></i></a>
                    </div>
                  </div>
            </div>
            <div class="modal" tabindex="-1" id="modal{{$game->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title {{$game->id}}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>Modal body text goes here.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <form action="{{route('games.destroy',compact('game'))}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger my-4">Elimina</button>
                        </form>
                    </div>
                    </div>
                </div>
            </div>
            @endforeach
            <div class="d-flex justify-content-center mt-5">
                {{$games->links()}}
            </div>
        </div>
    </div>
    
    






</x-layout>

resources/views/games/show.blade.php
<x-layout>
    <x-slot name="title">Videogiochi</x-slot>
    <style>
        
    </style>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 text-center mt-5">
                <h1>Ecco i dettagli del videogioco<h1>
            </div>
            <div class="col-8">
                <div class="card my-3">
                    <img src="{{$game->img ? Storage::url($game->img) : 'https://picsum.photos/200'}}" class="card-img-top img-custom" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{$game->title}}</h5>
                      <p class="card-text">Categorie:</p>
                      <p class="card-text">Descrizione: {{$game->description}}</p>
                      <a href="{{route('games.edit', compact('game'))}}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
                      <a href="" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal{{$game->id}}"><i class="fas fa-trash"></i></a>
                    </div>
                    
                  </div>
            </div>
        </div>
    </div>
    <form action="{{route('games.destroy', compact('game'))}}" method="POST" id="form-delete">
    @csrf
    @method('DELETE')
    </form>

    <div class="modal" tabindex="-1" id="modal{{$game->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title {{$game->id}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{route('games.destroy',compact('game'))}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger my-4">Elimina</button>
                </form>
            </div>
            </div>
        </div>
    </div>






</x-layout>